common-obj-$(CONFIG_PL181) += pl181.o
common-obj-y += ssi-sd.o
common-obj-y += sd.o core.o
common-obj-$(CONFIG_SDHCI) += sdhci.o

obj-$(CONFIG_MILKYMIST) += milkymist-memcard.o
obj-$(CONFIG_OMAP) += omap_mmc.o
obj-$(CONFIG_PXA2XX) += pxa2xx_mmci.o
